[package]
  cjc-version = "1.1.0"
  name = "refine"
  description = "A compile-time type-safe ORM for Cangjie"
  version = "0.1.0"
  output-type = "static"

[dependencies]
sonyflake = "1.0.9"

[test-dependencies]
mariadb = {git = "https://gitcode.com/Cangjie-SIG/mariadb-driver.git", branch = "master"}
